### ISSUE TITLE
Suggestion: mask the email domain 

### ISSUE THREAD

**Issue by thallard** [ggwhite/go-masker#27]
Hi, 

Following my last issue #26, I think it's a good idea to add a parameter in your function `Email()` to mask the domain if the boolean is set as true. Right now, it's just adding 4 `*` on the email but it's very easy to reverse, here is an example:

`thomas@hallard.info -> tho***@hallard.info`
It's very easy with some researchs to find my first name. 

With the domain masking, it should looks like this and it's way difficult to reverse my email right now:
`thomas@hallard.info -> tho***@ha*****.info or tho***@*******.info`

I suggest to change the signature of the function to: 

```go
func Email(i string, maskDomain boolean) string {
	// ...
}
```

**Comment by ggwhite** [comment]
@thallard please see this [comment](https://github.com/ggwhite/go-masker/issues/26#issuecomment-1996628797)
use v2 and customize your masker
